name: hoomd-polymers 
channels:
  - conda-forge
dependencies:
  - foyer
  - freud
  - gsd
  - mbuild
  - numba
  - numpy
  - pip=22.2
  - pytest
  - pytest-cov
  - python=3.9
  - signac=1.7.0
  - signac-flow=0.18.1
  - pip:
      - git+https://github.com/cmelab/cmeutils.git@master
