name: hoomd-organics
channels:
  - conda-forge
dependencies:
  - boltons
  - foyer
  - freud
    #  - gmso>=0.11.0
  - gsd<3.0
  - hoomd=3.11=*cpu*
  - mbuild
  - numpy
  - openbabel
  - pip
  - py3Dmol
  - pydantic
  - pytest
  - pytest-cov
  - python=3.9
  - symengine
  - python-symengine
  - unyt
  - pip:
      - git+https://github.com/cmelab/cmeutils.git@master
      - git+https://github.com/cmelab/grits.git@main
      - git+https://github.com/mosdef-hub/gmso@main
