name: hoomd-organics-dev
channels:
  - conda-forge
dependencies:
  - foyer
  - freud
  - gsd<3.0
  - hoomd=3.11=*cpu*
  - mbuild
  - numpy
  - openbabel
  - pip
  - py3Dmol
  - pytest
  - pytest-cov
  - python=3.9
  - pre-commit
  - unyt <=2.9.2
  - sympy
  - boltons
  - symengine
  - python-symengine
  - pip:
      - git+https://github.com/cmelab/cmeutils.git@master
      - git+https://github.com/cmelab/grits.git@main
      - git+https://github.com/mosdef-hub/gmso.git@main
