name: fusion 
channels:
  - conda-forge
dependencies:
  - foyer
  - freud
  - gmso >= 0.11.0
  - gsd
  - hoomd<4.0=*gpu*
  - mbuild
  - numpy
  - openbabel
  - pip
  - py3Dmol
  - pytest
  - pytest-cov
  - python=3.9
  - unyt
  - pip:
      - git+https://github.com/cmelab/cmeutils.git@master
      - git+https://github.com/cmelab/grits.git@main
